// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Count() {
  return window['go']['libzome']['App']['Count']();
}

export function Decrypt(arg1) {
  return window['go']['libzome']['App']['Decrypt'](arg1);
}

export function Encrypt(arg1) {
  return window['go']['libzome']['App']['Encrypt'](arg1);
}

export function GetUUID() {
  return window['go']['libzome']['App']['GetUUID']();
}

export function GetUUIDPretty() {
  return window['go']['libzome']['App']['GetUUIDPretty']();
}

export function HandleEvents(arg1) {
  return window['go']['libzome']['App']['HandleEvents'](arg1);
}

export function InitDb() {
  return window['go']['libzome']['App']['InitDb']();
}

export function InitP2P(arg1) {
  return window['go']['libzome']['App']['InitP2P'](arg1);
}

export function LoadConfig(arg1) {
  return window['go']['libzome']['App']['LoadConfig'](arg1);
}

export function RefreshPlugins() {
  return window['go']['libzome']['App']['RefreshPlugins']();
}
