// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Decrypt(arg1:any):Promise<any>;

export function Encrypt(arg1:string):Promise<any>;

export function GetUUID():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function Shutdown():Promise<void>;
