// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {sql} from '../models';

export function Count():Promise<void>;

export function Decrypt(arg1:any):Promise<any>;

export function Encrypt(arg1:string):Promise<any>;

export function GetUUID():Promise<string>;

export function GetUUIDPretty():Promise<string>;

export function HandleEvents(arg1:context.Context):Promise<void>;

export function InitDb():Promise<sql.DB>;

export function InitP2P(arg1:context.Context):Promise<void>;

export function LoadConfig(arg1:{[key: string]: string}):Promise<void>;

export function RefreshPlugins():Promise<void>;
