// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseDb() {
  return window['go']['libzome']['App']['CloseDb']();
}

export function Count() {
  return window['go']['libzome']['App']['Count']();
}

export function DbRead(arg1, arg2) {
  return window['go']['libzome']['App']['DbRead'](arg1, arg2);
}

export function DbWrite(arg1, arg2, arg3) {
  return window['go']['libzome']['App']['DbWrite'](arg1, arg2, arg3);
}

export function Decrypt(arg1) {
  return window['go']['libzome']['App']['Decrypt'](arg1);
}

export function DumpBackup() {
  return window['go']['libzome']['App']['DumpBackup']();
}

export function Encrypt(arg1) {
  return window['go']['libzome']['App']['Encrypt'](arg1);
}

export function GetStats() {
  return window['go']['libzome']['App']['GetStats']();
}

export function GetUUID() {
  return window['go']['libzome']['App']['GetUUID']();
}

export function GetUUIDPretty() {
  return window['go']['libzome']['App']['GetUUIDPretty']();
}

export function HandleEvents(arg1) {
  return window['go']['libzome']['App']['HandleEvents'](arg1);
}

export function InitDb(arg1) {
  return window['go']['libzome']['App']['InitDb'](arg1);
}

export function InitP2P(arg1) {
  return window['go']['libzome']['App']['InitP2P'](arg1);
}

export function LoadConfig(arg1) {
  return window['go']['libzome']['App']['LoadConfig'](arg1);
}

export function RefreshPlugins() {
  return window['go']['libzome']['App']['RefreshPlugins']();
}

export function RestoreBackup(arg1) {
  return window['go']['libzome']['App']['RestoreBackup'](arg1);
}
