// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Decrypt(arg1) {
  return window['go']['libzome']['App']['Decrypt'](arg1);
}

export function Encrypt(arg1) {
  return window['go']['libzome']['App']['Encrypt'](arg1);
}

export function GetUUID() {
  return window['go']['libzome']['App']['GetUUID']();
}

export function Greet(arg1) {
  return window['go']['libzome']['App']['Greet'](arg1);
}

export function Shutdown() {
  return window['go']['libzome']['App']['Shutdown']();
}
