// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: zreplicate.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SqlCommandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Query
	DbName string `protobuf:"bytes,1,opt,name=dbName,proto3" json:"dbName,omitempty"`
	Query  string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *SqlCommandRequest) Reset() {
	*x = SqlCommandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zreplicate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SqlCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SqlCommandRequest) ProtoMessage() {}

func (x *SqlCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zreplicate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SqlCommandRequest.ProtoReflect.Descriptor instead.
func (*SqlCommandRequest) Descriptor() ([]byte, []int) {
	return file_zreplicate_proto_rawDescGZIP(), []int{0}
}

func (x *SqlCommandRequest) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *SqlCommandRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SqlCommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Response
	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *SqlCommandResponse) Reset() {
	*x = SqlCommandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zreplicate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SqlCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SqlCommandResponse) ProtoMessage() {}

func (x *SqlCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zreplicate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SqlCommandResponse.ProtoReflect.Descriptor instead.
func (*SqlCommandResponse) Descriptor() ([]byte, []int) {
	return file_zreplicate_proto_rawDescGZIP(), []int{1}
}

func (x *SqlCommandResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_zreplicate_proto protoreflect.FileDescriptor

var file_zreplicate_proto_rawDesc = []byte{
	0x0a, 0x10, 0x7a, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x72, 0x65, 0x73, 0x71, 0x6c, 0x69,
	0x74, 0x65, 0x22, 0x41, 0x0a, 0x11, 0x53, 0x71, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x62, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x30, 0x0a, 0x12, 0x53, 0x71, 0x6c, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x65, 0x0a, 0x08, 0x52, 0x65, 0x53, 0x71, 0x6c,
	0x69, 0x74, 0x65, 0x12, 0x59, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x71, 0x6c, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x72, 0x65,
	0x73, 0x71, 0x6c, 0x69, 0x74, 0x65, 0x2e, 0x53, 0x71, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x5f, 0x72, 0x65, 0x73, 0x71, 0x6c, 0x69, 0x74, 0x65, 0x2e, 0x53, 0x71, 0x6c, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x3d,
	0x0a, 0x1f, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x7a, 0x6f, 0x6d,
	0x65, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x7a, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x42, 0x0f, 0x7a, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_zreplicate_proto_rawDescOnce sync.Once
	file_zreplicate_proto_rawDescData = file_zreplicate_proto_rawDesc
)

func file_zreplicate_proto_rawDescGZIP() []byte {
	file_zreplicate_proto_rawDescOnce.Do(func() {
		file_zreplicate_proto_rawDescData = protoimpl.X.CompressGZIP(file_zreplicate_proto_rawDescData)
	})
	return file_zreplicate_proto_rawDescData
}

var file_zreplicate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_zreplicate_proto_goTypes = []interface{}{
	(*SqlCommandRequest)(nil),  // 0: proto_resqlite.SqlCommandRequest
	(*SqlCommandResponse)(nil), // 1: proto_resqlite.SqlCommandResponse
}
var file_zreplicate_proto_depIdxs = []int32{
	0, // 0: proto_resqlite.ReSqlite.SendSqlCommand:input_type -> proto_resqlite.SqlCommandRequest
	1, // 1: proto_resqlite.ReSqlite.SendSqlCommand:output_type -> proto_resqlite.SqlCommandResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_zreplicate_proto_init() }
func file_zreplicate_proto_init() {
	if File_zreplicate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_zreplicate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SqlCommandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zreplicate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SqlCommandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zreplicate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zreplicate_proto_goTypes,
		DependencyIndexes: file_zreplicate_proto_depIdxs,
		MessageInfos:      file_zreplicate_proto_msgTypes,
	}.Build()
	File_zreplicate_proto = out.File
	file_zreplicate_proto_rawDesc = nil
	file_zreplicate_proto_goTypes = nil
	file_zreplicate_proto_depIdxs = nil
}
